wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.6
    framework: catboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1682101867.563355
    t:
      1:
      - 1
      - 5
      - 7
      - 53
      - 55
      2:
      - 1
      - 5
      - 7
      - 53
      - 55
      3:
      - 2
      - 3
      - 13
      - 23
      4: 3.10.4
      5: 0.13.6
      8:
      - 1
      - 3
      - 5
device:
  desc: null
  value: cuda
gamma:
  desc: null
  value: 0.95
lr:
  desc: null
  value: 0.01
model:
  desc: null
  value: "Sequential(\n  (0): Linear(in_features=50, out_features=516, bias=True)\n\
    \  (1): BatchNorm1d(516, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)\n\
    \  (2): Dropout(p=0.3, inplace=False)\n  (3): LeakyReLU(negative_slope=0.1)\n\
    \  (4): Linear(in_features=516, out_features=258, bias=True)\n  (5): BatchNorm1d(258,\
    \ eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)\n  (6): Dropout(p=0.3,\
    \ inplace=False)\n  (7): ReLU()\n  (8): Linear(in_features=258, out_features=129,\
    \ bias=True)\n  (9): BatchNorm1d(129, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)\n\
    \  (10): Dropout(p=0.3, inplace=False)\n  (11): ReLU()\n  (12): Linear(in_features=129,\
    \ out_features=64, bias=True)\n  (13): BatchNorm1d(64, eps=1e-05, momentum=0.1,\
    \ affine=True, track_running_stats=True)\n  (14): Dropout(p=0.3, inplace=False)\n\
    \  (15): ReLU()\n  (16): Linear(in_features=64, out_features=32, bias=True)\n\
    \  (17): BatchNorm1d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)\n\
    \  (18): Dropout(p=0.3, inplace=False)\n  (19): ReLU()\n  (20): Linear(in_features=32,\
    \ out_features=2, bias=True)\n)"
weight_decay:
  desc: null
  value: 0.001
