wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.6
    framework: catboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.15
    start_time: 1681937112.092572
    t:
      1:
      - 1
      - 5
      - 7
      - 53
      - 55
      2:
      - 1
      - 5
      - 7
      - 53
      - 55
      3:
      - 3
      - 13
      - 23
      4: 3.9.15
      5: 0.13.6
      8:
      - 1
      - 5
device:
  desc: null
  value: cpu
gamma:
  desc: null
  value: 0.9
lr:
  desc: null
  value: 0.01
model:
  desc: null
  value: "Sequential(\n  (0): Linear(in_features=15, out_features=256, bias=True)\n\
    \  (1): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)\n\
    \  (2): Dropout(p=0.3, inplace=False)\n  (3): LeakyReLU(negative_slope=0.1)\n\
    \  (4): Linear(in_features=256, out_features=128, bias=True)\n  (5): BatchNorm1d(128,\
    \ eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)\n  (6): Dropout(p=0.3,\
    \ inplace=False)\n  (7): ReLU()\n  (8): Linear(in_features=128, out_features=64,\
    \ bias=True)\n  (9): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)\n\
    \  (10): Dropout(p=0.3, inplace=False)\n  (11): PReLU(num_parameters=1)\n  (12):\
    \ Linear(in_features=64, out_features=32, bias=True)\n  (13): BatchNorm1d(32,\
    \ eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)\n  (14): Dropout(p=0.3,\
    \ inplace=False)\n  (15): GELU(approximate='none')\n  (16): Linear(in_features=32,\
    \ out_features=16, bias=True)\n  (17): BatchNorm1d(16, eps=1e-05, momentum=0.1,\
    \ affine=True, track_running_stats=True)\n  (18): Dropout(p=0.3, inplace=False)\n\
    \  (19): ELU(alpha=1.0)\n  (20): Linear(in_features=16, out_features=2, bias=True)\n\
    )"
weight_decay:
  desc: null
  value: 0.001
