wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.6
    framework: catboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.15
    start_time: 1681912338.641104
    t:
      1:
      - 1
      - 5
      - 7
      - 53
      - 55
      2:
      - 1
      - 5
      - 7
      - 53
      - 55
      3:
      - 3
      - 13
      - 23
      4: 3.9.15
      5: 0.13.6
      8:
      - 1
      - 5
device:
  desc: null
  value: cpu
gamma:
  desc: null
  value: 0.9
lr:
  desc: null
  value: 0.01
model:
  desc: null
  value: "Sequential(\n  (0): Linear(in_features=30, out_features=500, bias=True)\n\
    \  (1): BatchNorm1d(500, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)\n\
    \  (2): ReLU()\n  (3): Dropout(p=0.2, inplace=False)\n  (4): Linear(in_features=500,\
    \ out_features=1000, bias=True)\n  (5): BatchNorm1d(1000, eps=1e-05, momentum=0.1,\
    \ affine=True, track_running_stats=True)\n  (6): ReLU()\n  (7): Dropout(p=0.2,\
    \ inplace=False)\n  (8): Linear(in_features=1000, out_features=500, bias=True)\n\
    \  (9): BatchNorm1d(500, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)\n\
    \  (10): ReLU()\n  (11): Dropout(p=0.2, inplace=False)\n  (12): Linear(in_features=500,\
    \ out_features=400, bias=True)\n  (13): BatchNorm1d(400, eps=1e-05, momentum=0.1,\
    \ affine=True, track_running_stats=True)\n  (14): ReLU()\n  (15): Dropout(p=0.2,\
    \ inplace=False)\n  (16): Linear(in_features=400, out_features=300, bias=True)\n\
    \  (17): BatchNorm1d(300, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)\n\
    \  (18): ReLU()\n  (19): Dropout(p=0.2, inplace=False)\n  (20): Linear(in_features=300,\
    \ out_features=200, bias=True)\n  (21): BatchNorm1d(200, eps=1e-05, momentum=0.1,\
    \ affine=True, track_running_stats=True)\n  (22): ReLU()\n  (23): Dropout(p=0.2,\
    \ inplace=False)\n  (24): Linear(in_features=200, out_features=100, bias=True)\n\
    \  (25): BatchNorm1d(100, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)\n\
    \  (26): ReLU()\n  (27): Dropout(p=0.2, inplace=False)\n  (28): Linear(in_features=100,\
    \ out_features=2, bias=True)\n)"
weight_decay:
  desc: null
  value: 0.001
